## Author: Author: Rodrigo Marins Piaba (Fanaticos4tech)

## E-Mail: rodrigomarinsp@gmail.com / fanaticos4tech@gmail.com

## GitHub: github.com/rodrigomarinsp/github-security-pipeline

## Website: http://github.com/rodrigomarinsp/github-security-pipeline/index.html

blank_issues_enabled: false
contact_links:
  - name: GitHub Security Pipeline Community Support
    url: https://github.com/yourusername/github-security-pipeline/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Pipeline Security Issues
    url: https://security-pipeline.example.com/security
    about: Please report security vulnerabilities here.
